# Generated by Django 5.1.7 on 2025-03-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_university_admin_alter_university_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='admin',
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
