# Generated by Django 5.1.7 on 2025-03-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_university_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandatorysubject',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='mandatorysubject',
            name='universities',
            field=models.ManyToManyField(related_name='mandatory_subjects', to='core.university'),
        ),
    ]
