# Generated by Django 5.1.7 on 2025-03-15 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_alter_university_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='university',
            table='universities',
        ),
    ]
