# Generated by Django 5.1.7 on 2025-03-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_alter_university_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='required_courses_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
