# Generated by Django 5.1.7 on 2025-03-17 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_university_required_courses_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='required_average_rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
