# Generated by Django 3.2 on 2025-03-16 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20250316_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='type',
        ),
    ]
