# Generated by Django 3.2 on 2025-03-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='courses',
            field=models.ManyToManyField(related_name='professors', to='main.Course'),
        ),
    ]
