# Generated by Django 3.2 on 2025-03-16 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_professor_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='professor',
        ),
    ]
