# Generated by Django 3.2 on 2025-03-16 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_course_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='university',
        ),
        migrations.AddField(
            model_name='course',
            name='professor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main.professor'),
            preserve_default=False,
        ),
    ]
