# Generated by Django 3.2 on 2025-03-16 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20250316_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='courses',
        ),
    ]
