# Generated by Django 3.2 on 2025-03-16 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_university_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='university',
            field=models.ForeignKey(default=432, on_delete=django.db.models.deletion.CASCADE, to='main.university'),
            preserve_default=False,
        ),
    ]
