# Generated by Django 5.1.7 on 2025-03-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_graduationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduationrequest',
            name='average_grade',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='graduationrequest',
            name='total_courses',
            field=models.IntegerField(default=0),
        ),
    ]
