# Generated by Django 5.1.7 on 2025-03-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_graduationrequest_average_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduationrequest',
            name='per_course_averages',
            field=models.JSONField(default=dict),
        ),
    ]
