# Generated by Django 5.1.7 on 2025-03-17 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_graduationrequest_per_course_averages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduationrequest',
            name='average_grade',
        ),
    ]
