# Generated by Django 5.1.7 on 2025-03-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_graduationrequest_average_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='graduation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
